name: Build & Deploy to GKE GCP2

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: my-projectfeb1
  REGION: asia-south1
  CLUSTER_NAME: cluster-1
  CLUSTER_LOCATION: asia-south1-b	
  REPOSITORY: asia-south1-docker.pkg.dev/my-projectfeb1/cloud-run-source-deploy
  IMAGE_NAME: my-app

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write # REQUIRED for Workload Identity Federation

    steps:
      # -----------------------------
      # Checkout code
      # -----------------------------
      - name: Checkout code
        uses: actions/checkout@v4

      # -----------------------------
      # Authenticate to GCP using WIF
      # -----------------------------
      - id: 'auth'
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          create_credentials_file: 'true'
          workload_identity_provider: projects/704009009226/locations/global/workloadIdentityPools/github/providers/github-provider
          service_account: githubaction@my-projectfeb1.iam.gserviceaccount.com

      # -----------------------------
      # Setup gcloud
      # -----------------------------
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      # -----------------------------
      # Configure Docker for Artifact Registry
      # -----------------------------
      - name: Configure Docker
        run: |
          gcloud auth configure-docker $REGION-docker.pkg.dev --quiet

      # -----------------------------
      # Build & Push Docker Image
      # -----------------------------
      - name: Build and Push Image
        run: |
          IMAGE_URI="$REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:${{ github.sha }}"
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

      # -----------------------------
      # Get GKE credentials
      # -----------------------------
      - name: Get GKE Credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ env.CLUSTER_NAME }}
          location: ${{ env.CLUSTER_LOCATION }}

      # -----------------------------
      # Deploy to GKE
      # -----------------------------
      - name: Deploy to GKE
        run: |
          sed -i "s|IMAGE_PLACEHOLDER|$IMAGE_URI|g" deployment.yaml
          kubectl apply -f deployment.yaml
